Einbau Feature-Toggle
Ikoki13/AutomatedCatsEntries pull request #11
Opened 2024-04-02 20:05 UTC by danielundeutsch

- Anpassung der CATsRow.py durch herauslösen der addEntriesToCATsCells() Function aus dem Konstruktor
- Einbau eines Feature-Toggles in der CATsRow.py, um zwischen SingleBlock Entries und getrennten Entries mit Termin und Ohne Termin zu switchen
- Anpassung der README.md mit der neuen Funktionalität des Feature-Toggles

2024-04-07 06:32 UTC, Ikoki13 commented on configFileApp.py
> +    def writeConfigFile(self):
wo wird diese Funktion verwendet?

2024-05-21 07:28 UTC, Ikoki13 requested changes

2024-05-21 07:28 UTC, Ikoki13 commented on Classes/updater.py
wieso wird ein updater benötigt?

2024-05-21 07:28 UTC, Ikoki13 commented on main.py
> +if autoUpdaterEnabled:
gleiche Frage wie oben - wieso wird ein Updater benötigt?

2024-05-26 16:13 UTC, danielundeutsch commented on Classes/updater.py
Um in späterer Folge bei weiteren Updates die Software nicht erneut downloaden zu müssen, sondern ein auto-update durchzuführen

2024-06-13 07:04 UTC, Ikoki13 commented on Classes/updater.py
Bitte entfernen oder in einen separaten Branch geben damit der separat getestet werden kann

2025-01-17 13:38 UTC, closed without merging